# Generated by Django 4.1.1 on 2023-02-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hubuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
