# Generated by Django 4.1.1 on 2023-02-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
