# Generated by Django 4.1.1 on 2023-04-05 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0004_rename_user_id_wallet_user_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingplan',
            old_name='wallet_id',
            new_name='wallet',
        ),
    ]
