# Generated by Django 4.1.7 on 2024-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0007_remove_transaction_from_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customlabel',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customlabel',
            old_name='user',
            new_name='wallet',
        ),
        migrations.AlterField(
            model_name='customlabel',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
