# Generated by Django 4.1.7 on 2024-02-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0008_rename_title_customlabel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubuser',
            name='avatar',
        ),
    ]
