# Generated by Django 4.1.7 on 2024-03-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0010_alter_transaction_date'),
        ('hubModels', '0010_remove_transaction_description_transaction_imported_and_more'),
    ]

    operations = [
    ]
