# Generated by Django 4.1.7 on 2024-03-09 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubModels', '0011_merge_20240309_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recurrency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hubModels.transactionrecurrency'),
        ),
    ]
