# Generated by Django 4.1.1 on 2023-02-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubUser.hubuser')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('INCOME', 'Income')], max_length=100)),
                ('user_label', models.CharField(blank=True, max_length=30, null=True)),
                ('from_user', models.CharField(blank=True, max_length=50, null=True)),
                ('to_user', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=200)),
                ('update_wallet', models.BooleanField(default=True)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubModels.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('goal_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('wallet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubModels.wallet')),
            ],
        ),
    ]
